### PR TITLE
Create minified dist file

### LINKED ISSUE #96: Host minified dist file on UNPKG
As a follow-on to https://github.com/emeeks/semiotic/issues/93#issuecomment-346201111 and https://github.com/emeeks/semiotic/pull/92 , the final task for a prim and proper UNPKG distribution is to include a minified version. The unminified dist file is fairly large at 1.2MB.

We may even want to consider _only_ including the minified version, as presently anyone who `npm install`s Semiotic will have to eat an extra 1.2MB download.

When this id done, a minified file should appear in this list here: [https://unpkg.com/semiotic@1.2.7/dist/](https://unpkg.com/semiotic@1.2.7/dist/)

### PR DESCRIPTION
**Pull request by curran**
Closes #96

### CODE REVIEW

**Comment by curran** [comment]
@emeeks Note: This PR leaves the unminified version in NPM.

If you want to only put the minified file in NPM, you can append ` && rm ./dist/semiotic.js` to the `prepublish` script like this:

```
"prepublish": "rollup -c && uglifyjs ./dist/semiotic.js -o ./dist/semiotic.min.js && rm ./dist/semiotic.js"
```

**Comment by emeeks** [comment]
Thanks, Curran, am I right in understanding that folks that `npm i` this package are now also getting the minified dist along with the original `/lib/` directory? If so, is there a solution for people that want to include the modules but not the dist somehow? If not, then thanks for the patience, this build stuff is not my thing.

**Comment by curran** [comment]
@emeeks Yes that's right. My understanding is that the way UNPKG works is to automatically run `npm i`, then serve whatever files show up from that. So whatever files show up via UNPKG are the same files that folks get after running `npm i`.

To the best of my knowledge, there is not currently a way to have the dist files included in UNPKG, but excluded from the files fetched when people do an `npm i`.

**Comment by curran** [comment]
@emeeks Just one more `npm publish` and we will reach UNPKG nirvana

**Pull request merged**
