### PR TITLE
Add and configure rollup

### LINKED ISSUE #70: Build unpkg-compatible distribution file?
Hello Elijah!

Would there be interest in building a browser-compatible `dist` file so that users could load semiotic from a service like [unpkg](https://unpkg.com/)? This would likely mean running `rollup` on `prepublish` and including the dist file as an entry point under the `unpkg` or `browser` field in package.json ([as mentioned under unpkg's main notes](https://unpkg.com/#/)). If so, happy to take a pass at contributing such a thing.

- Tom

### PR DESCRIPTION
**Pull request by tmcw**
Fixes #70 

Here we go: semiotic, usable as a script tag! Notes:

* element-resize-event has a [bug in 2.0.9](https://github.com/KyleAMathews/element-resize-event/issues/19) so I've backtracked it to 2.0.7.
* A few libraries that semiotic relies on - json2csv in particular - rely on node builtin modules like `os`, so I'm including a rollup plugin that maps those to their browserify-ish equivalents. I don't see anywhere that we're really relying on node core solving ' hard parts' so to speak so it'd be a good goal down the line to switch to less node-ish dependencies or PR in improvements to them.
* Rollup & [some gurus](http://exploringjs.com/es6/ch_modules.html#_recommendation-avoid-mixing-default-exports-and-named-exports) dissuade the practice of exporting both default and named values. This causes a minor warning in Rollup - it still works, but might be a continuing nag.
* Rollup also complains about [this passage of DownloadButton](https://github.com/emeeks/semiotic/blob/master/src/components/DownloadButton.js#L15). I'd like to refactor that section - no strong need to play with the fire that is `this` in JavaScript when you can save a reference to the href.

Besides that... well, requisite example: https://jsfiddle.net/tmcw/69z2wepo/91934/

* Question: I don't know how your ideal publish flow works. For this kind of thing, my usual formula is to put UMD build tasks in a `prepublish` step. In this case, though, maybe they belong in the `publish-release` task? Your call for how you want that to work.
* What's the plan with babel configuration? The presets included in package.json don't have any overlap with the ones specified in babelrc. Is the plan to migrate to the netflix-dea preset? For now, I'm modeling the rollup babel configuration after the one in babelrc.

### CODE REVIEW

**Comment by emeeks** [comment]
Hey Tom, this is wonderful. I'm going to fix the DownloadButton bit and to answer your questions, at the risk of sounding foolish, I haven't thought too much about the build script and babel and have just been using the settings of the repo as it was set up by someone else long ago. I'm always open to better practice if you have suggestions.

**Comment by curran** [comment]
Very exciting! Thanks a ton for doing this.

@tmcw I was able to reproduce your fiddle in bl.ocks.org https://bl.ocks.org/curran/8407fbc3d04d5ca06d8045ccaa4cf202/f35b4e70e13e1bd68ef69d42e9d56b282b58194d

It's using @tmcw 's hosted Semiotic build for now.

The next step would be to get this on UNPKG with UMD build tasks in a `prepublish` step.

**Comment by curran** [comment]
When I run `rollup -c`, I get the following error:

```
> rollup -c

src/components/index.js → dist/semiotic.js...
[!] Error: Could not resolve './arrowhead' from node_modules/d3-glyphedge/src/d3-glyphEdge.js
Error: Could not resolve './arrowhead' from node_modules/d3-glyphedge/src/d3-glyphEdge.js
    at error (/home/curran/repos/semiotic/node_modules/rollup/dist/rollup.js:185:14)
    at then.resolvedId (/home/curran/repos/semiotic/node_modules/rollup/dist/rollup.js:10124:8)
    at <anonymous>
```

Have you come across this error before?

**Comment by tmcw** [comment]
@curran yep, that's the command I run and it works on my computer and I know why it doesn't work on yours and it will make everyone wince :)

I'm running a Mac, you're on Linux (or something linux-ish). Your filesystem is case-sensitive, mine isn't. The d3-glyphEdge module requires `./arrowhead` in the npm package, but the file on disk is `./arrowHead`. So, it works on my computer because on my filesystem the two are equivalent, but not on yours because it's strict.

Fix would be in the `d3-glyphEdge` package, or get a time machine back to when someone thought that case-insensitive file systems were a good idea and convince them not to do it :)

**Comment by emeeks** [comment]
I'll make sure to fix this in `d3-glyphEdge` and update the version.

**Comment by curran** [comment]
@tmcw Aha! That's a great insight re: case-sensitivity. Indeed I'm on Linux.

@emeeks Thanks for fixing in `d3-glyphEdge`! Now it builds fine on my system.

Just sent a PR for minification which should wrap up this saga https://github.com/emeeks/semiotic/pull/97

Very exciting!

**Pull request merged**
