### PR TITLE
WIP: Add rollup build in prepublish

### LINKED ISSUE #93: Host distribution files on UNPKG
As a follow-on to https://github.com/emeeks/semiotic/issues/70 and https://github.com/emeeks/semiotic/pull/92 , the built files need to go into NPM to get exposed via UNPKG.

This can be done by putting build tasks in a `prepublish` step, much the same way as the D3 modules do it, for example https://github.com/d3/d3-selection/blob/master/package.json#L28

### PR DESCRIPTION
**Pull request by curran**
This should close #93

### CODE REVIEW

**Comment by curran** [comment]
```
Currently WIP, stuck with the following error:

> rollup -c


src/components/index.js → dist/semiotic.js...
[!] Error: Could not resolve './arrowhead' from node_modules/d3-glyphedge/src/d3-glyphEdge.js
Error: Could not resolve './arrowhead' from node_modules/d3-glyphedge/src/d3-glyphEdge.js
    at error (/home/curran/repos/semiotic/node_modules/rollup/dist/rollup.js:185:14)
    at then.resolvedId (/home/curran/repos/semiotic/node_modules/rollup/dist/rollup.js:10124:8)
    at <anonymous>
```

**Comment by emeeks** [comment]
I saw this, too, this morning. And here I thought everything was automated in the future!

**Comment by curran** [comment]
@emeeks Does the prepublish script run for you, without that error?

**Comment by emeeks** [comment]
Yes the script runs fine and creates `semiotic.js` in `/dist/` the problem comes when I refer to the file from Codepen when it complains about `babelHelpers`.

**Comment by curran** [comment]
Oh great! Did you include babel-standalone in the pen? See this example http://bl.ocks.org/curran/8407fbc3d04d5ca06d8045ccaa4cf202/9b37855e4d7482ae2666225ef2770e4dab8420bb

It works from UNPKG! Woooooo :tada:

**Pull request merged**
