### PR TITLE
Allow setting the position of boxplot summaries

### PR DESCRIPTION
**Pull request by jeffreypriebe**
ORFrame now accepts a `summaryPosition` function (optional, default will be backwards compatible behavior) that will be passed the calculated position for the OR summary as well as the current context (`key, summaryI`) and translate the labels to the return value.

This is passed from ORFrame down through framefunctions into summaryDrawing as `positionFn`.

Applied to vertical & horizontal projections.
Applied to boxplot summaries.

### CODE REVIEW

**Comment by emeeks** [comment]
Can you explain a use case for this?

**Comment by jeffreypriebe** [comment]
I meant to include the use case.

I have data that is two groups and I'm displaying it as boxplot summaries. I want each of the two groups' boxplots to be next to eachother.
screen shot 2017-09-08 at 12 06 17 pm

**Comment by emeeks** [comment]
Sure that makes sense, let's give it a try. Could you please document it in the API wiki?

**Comment by jeffreypriebe** [comment]
[Documentation added to API wiki](https://github.com/emeeks/semiotic/wiki/OrdinalFrame/_compare/34e4a3d849464d8adef7d1fe865d26fbecd1f896...04dfe4b8a8ca3589d7b415202ab5ad9afd40cda6).

**Pull request merged**
