### PR TITLE
fix: rm npm warnings

### PR DESCRIPTION
**Pull request by jameswomack**
1. [x] Remove Netflix Artifactory registry security breach & network error in package-lock.json
1. [x] Install more recent, better supported versions of some dependencies
1. [x] Install some versions of dependencies that better match sibling dependencies
1. [x] Remove unused JSCS that had a transient dependency on the deprecated minimatch 2
1. [x] Call `injectTapEvent` in accordance with the ES2015 modules specification

Regarding #1, the issue is that a package-lock was created from within the Netflix VPN zone / with the Netflix .npmrc configuration. This is not ideal security-wise, while also not ideal for users of Semiotic as installation using those URIs will inevitably fail unless they work at Netflix & are inside the Netflix VPN zone.

Resolved the following warnings:
```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

"/Users/jwomack/Projects/github/emeeks/semiotic/node_modules/react-scripts/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" (not found)
node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v57-darwin-x64.tar.gz
node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download: https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.14 and node@8.2.1 (node-v57 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http Pre-built binary not available for your system, looked for https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v57-darwin-x64.tar.gz
node-pre-gyp verb command build [ 'rebuild' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
2017-10-05 13:23:40.105 xcodebuild[22867:531053] [MT] PluginLoading: Required plug-in compatibility UUID DF11C142-1584-4A99-87AC-1925D5F5652A for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/NCSimulatorPlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-10-05 13:23:40.106 xcodebuild[22867:531053] [MT] PluginLoading: Required plug-in compatibility UUID DF11C142-1584-4A99-87AC-1925D5F5652A for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/DerivedData Exterminator.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-10-05 13:23:40.107 xcodebuild[22867:531053] [MT] PluginLoading: Required plug-in compatibility UUID DF11C142-1584-4A99-87AC-1925D5F5652A for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ColorSenseRainbow.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-10-05 13:23:40.109 xcodebuild[22867:531053] [MT] PluginLoading: Required plug-in compatibility UUID DF11C142-1584-4A99-87AC-1925D5F5652A for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CocoaPods.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-10-05 13:23:40.110 xcodebuild[22867:531053] [MT] PluginLoading: Required plug-in compatibility UUID DF11C142-1584-4A99-87AC-1925D5F5652A for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/BuildTimeAnalyzer.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-10-05 13:23:40.111 xcodebuild[22867:531053] [MT] PluginLoading: Required plug-in compatibility UUID DF11C142-1584-4A99-87AC-1925D5F5652A for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Anglerfish.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-10-05 13:23:40.112 xcodebuild[22867:531053] [MT] PluginLoading: Required plug-in compatibility UUID DF11C142-1584-4A99-87AC-1925D5F5652A for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  COPY /Users/jwomack/Projects/github/emeeks/semiotic/node_modules/react-scripts/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp
node-pre-gyp info ok
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN react-element-to-jsx-string@2.2.0 requires a peer of react@^0.14.0 but none was installed.
npm WARN react-addons-test-utils@0.14.8 requires a peer of react@^0.14.8 but none was installed.
npm WARN eslint-config-react-app@0.5.2 requires a peer of babel-eslint@^7.0.0 but none was installed.
npm WARN eslint-config-react-app@0.5.2 requires a peer of eslint@^3.8.1 but none was installed.
npm WARN eslint-config-react-app@0.5.2 requires a peer of eslint-plugin-react@^6.4.1 but none was installed.
npm WARN eslint-loader@1.6.0 requires a peer of eslint@>=1.6.0 <4.0.0 but none was installed.
npm WARN eslint-plugin-import@2.0.1 requires a peer of eslint@2.x - 3.x but none was installed.
npm WARN eslint-plugin-jsx-a11y@2.2.3 requires a peer of eslint@^2.10.2 || 3.x but none was installed.
```

### CODE REVIEW

**Comment by stormasm** [comment]
This commit breaks the code...  When I try and bring up the server after re-running yarn / npm server throws an error.  When I revert back to tag v1.1.4 everything works again...  One of the new package replacements somehow is messing something up...

**Comment by emeeks** [comment]
I made a few updates and such with 1.1.6 and it seems to be working fine now @stormasm but let me know if you still see any problems.

**Comment by stormasm** [comment]
@emeeks I just pulled from master 1.1.6 and its all working again, thanks for fixing this...  On an unrelated note, in the future if I have a question about semiotic what is the best way for me to contact you ?  Are you OK with sending an email to you ?  Thanks --- Michael

**Comment by emeeks** [comment]
I'd prefer to keep any feature requests or other issues here so that everyone can see them but if it's longer/more involved or something then feel free to email me.

**Pull request merged**
