### PR TITLE
Try to render a few different examples

### PR DESCRIPTION
**Pull request by emeeks**
Doesn't seem to be generating a screenshot of all the examples just the first one in the array of elements (the bar chart).

### CODE REVIEW

**Comment by rgbkrk** [comment]
It looks like, based on the screenshot that dimensions for the element and the puppeteer page need to be changed.

**Comment by emeeks** [comment]
I already changed `page.setViewport` and also the sizes of the individual components I was rendering but it still only seems to render the first element in the array of elements I send.

**Comment by rgbkrk** [comment]
Taking this for a spin locally to see what I can do.

**Comment by rgbkrk** [comment]
There is a lot of whitespace between examples. Oh! I see it. The div around each responsive container from semiotic has a ridiculous height of 100% and width of 100%, inherited from `ResponsiveFrame` it looks like?

**Comment by rgbkrk** [comment]
To figure this out I changed puppeteer's launch params to the following:

```js
-  const browser = await puppeteer.launch()
+  const browser = await puppeteer.launch({
+    headless: false,
+    devtools: true
+  })
```

**Pull request merged**
